### ISSUE TITLE
issue with creating an object for "generationconfig" in the BuildGeminiRequest method. 

### ISSUE THREAD

**Issue by Krishna-Mouli** [gsilvamartin/dotnet-gemini-sdk#1]
hey bro, great package, helped a lot but i keep getting this issue every time i try to pass hyper parameters to the model, for that I'm using the same object that you created in the GeminiMessageRequest.cs class which is GenerationConfig, but I feel the BuildGeminiRequest in the GeminiClient is causing an issue which creates the payload for the request, to be precise this is the issue, 

 "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"generationconfig\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"generationconfig\": Cannot find field."
          }
        ]
      }
    ]
  }
}

I feel the property name is being set in a wrong way, as per google's docs the property name should be "generationConfig". Can you please look into this?, thanks. The c should be in caps in the payload while we send the request.

**Comment by Krishna-Mouli** [comment]
[JsonProperty("generationconfig", NullValueHandling = NullValueHandling.Ignore)]
    public GenerationConfig? GenerationConfig { get; set; }, 
  
  Please change the property name to Camel Case

**Comment by gsilvamartin** [comment]
Hi @Krishna-Mouli !

Will fix it today, thanks for sharing!!

**Comment by Krishna-Mouli** [comment]
Awesome!!
